spring:
  application:
    name: corporate-banking-backend

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/corporate_banking_db}


server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info


